add public_accessors option
pawurb/smart_init pull request #5
Opened 2020-04-11 10:38 UTC by morgvanny

following up on #4 

hopefully this makes sense! I didn't have a problem with the existing implementation, but when I tried to add the feature, I ended up making a huge mess. cleaning that up, I found some ways to simplify the logic in general I think

2020-04-11 17:34 UTC, pawurb requested changes
Looking good, just small changes needed. And thanks for a refactor. Please also add info to readme.

2020-04-11 17:34 UTC, pawurb commented on lib/smart_init/main.rb
> +      parameters == [] ? parameters = {} : parameters = parameters.first
maybe:

```
       parameters = parameters == [] ? {} : parameters.first
```

2020-04-11 17:34 UTC, pawurb commented on lib/smart_init/main.rb
> +  def initialize_with_hash(*required_attrs, **hash)
hash is a global ruby method please rename to prevent shadowing

2020-04-11 17:37 UTC, pawurb commented on lib/smart_init/main.rb
> +      parameters == [] ? parameters = {} : parameters = parameters.first
or  even more readable:

```
parameters = if parameters == []
  {}
else
  parameters.first
end
```

2020-04-11 23:53 UTC, morgvanny commented
Thanks for the prompt review! I think I've resolved each of those issues now

2020-04-12 09:50 UTC, merged

2020-04-12 09:50 UTC, pawurb commented
Thanks!